app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/jdbc-template
      password: '@Potter77'
      pool-size: 30
      username: 'root'

server:
  error:
    include-binding-errors: always
    include-message: always


